spring:
  application:
    name: pocket-market-main
  profiles:
    active:
    - prod
---
spring:
  profiles: prod 
  datasource:
    url: jdbc:postgresql://localhost:5432/pocket_market
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true
  resources:
    static-locations:
    - file:///D://pm
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
server:
  port: 8083
management:
  endpoint:
    beans:
      enabled: true
    metrics:
      enabled: true
    web:
      exposure:
        include: "*"
logging:
  level:
    com.pm : INFO
storage:
  upload-dir: 'D:\pm'
  
cloud:
  aws:
    region:
      static: eu-west-1
    stack:
      auto: false